site_name: Glimmr

nav:
  - Welcome: index.md
  - Installation: install.md
  - First Program: firstprogram.md
  - Literals: literals.md
  - Operators: operators.md
  - Types: types.md
  - Type Inference: inference.md
  - Functions: functions.md

extra_javascript:
  - assets/js/highlight.min.js
  - assets/js/glimmr.js

extra_css:
  - assets/style/css.css

theme: bootstrap386
-- theme: readthedocs


